/** Catálogo Anexo A — Manual Comercio Electrónico Banorte v2.1 (PAYW_CODE). */
export const CATALOGO_PAYW_ES: Record<string, string> = {
  'PAYW-0201': 'El acceso al almacén de llaves (keystore) fue denegado',
  'PAYW-0202': 'Incapaz de establecer conexión con servidor xxx',
  'PAYW-0203': 'No se tiene conexión actualmente con el servidor. Se intenta reconexión',
  'PAYW-1002': 'El mensaje ISO recibido contiene una TPDU no válida',
  'PAYW-1004': 'El mensaje ISO recibido tiene un terminador no válido',
  'PAYW-1007': 'El contenido del campo excede el máximo permitido',
  'PAYW-1009': 'El juego de caracteres ISO-8859-1 no está soportado',
  'PAYW-1010': 'El campo está incompleto en el mensaje ISO',
  'PAYW-1011': 'El campo no es válido',
  'PAYW-1013': 'El contenido del campo no es válido',
  'PAYW-1014': 'El modo de entrada (campo 22) no es válido',
  'PAYW-1017': 'No ha sido posible identificar el tipo de transacción',
  'PAYW-1018': 'La información de promoción Q6 es inválida',
  'PAYW-2010': 'No se especificó el parámetro requerido CMD_TRANS',
  'PAYW-2011': 'El comando o transacción no es válido o no está soportado',
  'PAYW-2014': 'El parámetro no puede ser nulo',
  'PAYW-2015': 'URL de respuesta no válida',
  'PAYW-3001': 'Incapaz de realizar la operación. Por favor intente más tarde',
  'PAYW-3002': 'La afiliación o el usuario proporcionados no existen',
  'PAYW-3003': 'Usuario o contraseña inválidos',
  'PAYW-3004': 'La afiliación no se encuentra activa',
  'PAYW-3008': 'La terminal no existe para esta afiliación',
  'PAYW-3010': 'Transacción no permitida para esta terminal y marca de tarjeta',
  'PAYW-3011': 'El comando no está soportado actualmente',
  'PAYW-3012': 'La transacción referenciada no existe',
  'PAYW-3039': 'El número de control ya existe para una transacción',
  'PAYW-3040': 'No se permite monto cero en una transacción',
  'PAYW-3041': 'El modo de entrada de la transacción no es compatible',
  'PAYW-3058': 'Transacción rechazada, utilice lector chip',
  'PAYW-4017': 'Número de tarjeta inconsistente',
  'PAYW-4018': 'El tiempo máximo de espera para la transacción ha sido excedido',
  'PAYW-6107': 'La cuenta del cliente está bloqueada',
  'PAYW-6109': 'No se permiten más operaciones en la tarjeta',
  'PAYW-7100': 'La transacción no contiene información válida.',
  'PAYW-9999': 'Falla inesperada en la aplicación.',
}
