-- Situación delicada del alumno (ficha Servicios / datos elementales).
-- Una fila por alumno_id; el check "No corresponde" indica que no hay caso.

CREATE TABLE IF NOT EXISTS public.alumno_situacion_delicada (
  situacion_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alumno_id integer NOT NULL REFERENCES public.alumno (alumno_id) ON DELETE CASCADE,
  no_corresponde boolean NOT NULL DEFAULT true,
  comentarios text NOT NULL DEFAULT '',
  actualizado_por text NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT alumno_situacion_delicada_alumno_id_key UNIQUE (alumno_id)
);

COMMENT ON TABLE public.alumno_situacion_delicada IS
  'Situación delicada en ficha del alumno. no_corresponde = sin caso; comentarios cuando sí aplica.';

CREATE INDEX IF NOT EXISTS alumno_situacion_delicada_caso_idx
  ON public.alumno_situacion_delicada (alumno_id)
  WHERE no_corresponde = false;

DROP TRIGGER IF EXISTS alumno_situacion_delicada_updated_at ON public.alumno_situacion_delicada;
CREATE TRIGGER alumno_situacion_delicada_updated_at
  BEFORE UPDATE ON public.alumno_situacion_delicada
  FOR EACH ROW
  EXECUTE FUNCTION system.update_updated_at();

ALTER TABLE public.alumno_situacion_delicada ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.alumno_situacion_delicada FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS servicios_insforge_deny_anon ON public.alumno_situacion_delicada;
CREATE POLICY servicios_insforge_deny_anon ON public.alumno_situacion_delicada
  FOR ALL TO anon, authenticated USING (false) WITH CHECK (false);
REVOKE ALL ON public.alumno_situacion_delicada FROM anon, authenticated;
