-- Winston Servicios: esquema migrado desde Supabase (MySQL legacy)
-- Orden: funciones → tablas base → hijas → FKs

-- === Triggers alumno / becas ===
CREATE OR REPLACE FUNCTION public.set_updated_at_timestamp()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN NEW.alumno_actualizacion := CURRENT_TIMESTAMP; RETURN NEW; END; $$;

CREATE OR REPLACE FUNCTION public.set_detalle_updated_at_timestamp()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN NEW.detalle_actualizacion := CURRENT_TIMESTAMP; RETURN NEW; END; $$;

CREATE OR REPLACE FUNCTION public.set_familiar_updated_at_timestamp()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN NEW.familiar_actualizacion := CURRENT_TIMESTAMP; RETURN NEW; END; $$;

CREATE OR REPLACE FUNCTION public.set_contacto_updated_at_timestamp()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN NEW.contacto_actualizacion := CURRENT_TIMESTAMP; RETURN NEW; END; $$;

CREATE OR REPLACE FUNCTION public.set_beca_updated_at_timestamp()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN NEW.beca_actualizacion := CURRENT_TIMESTAMP; RETURN NEW; END; $$;

CREATE OR REPLACE FUNCTION public.set_pago_detalle_actualizacion_timestamp()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN NEW.pago_actualizacion := CURRENT_TIMESTAMP; RETURN NEW; END; $$;

CREATE OR REPLACE FUNCTION public.set_pago_interno_actualizacion_timestamp()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN NEW.pago_actualizacion := CURRENT_TIMESTAMP; RETURN NEW; END; $$;

CREATE OR REPLACE FUNCTION update_ciclo_escolar_updated_at()
RETURNS TRIGGER AS $$
BEGIN NEW.updated_at = CURRENT_TIMESTAMP; RETURN NEW; END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION asegurar_un_ciclo_actual()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.es_actual = true THEN
    UPDATE public.ciclos_escolares SET es_actual = false WHERE id != NEW.id;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- === Catálogos ===
CREATE TABLE IF NOT EXISTS public.ciclos_escolares (
  id SERIAL PRIMARY KEY,
  valor SMALLINT NOT NULL UNIQUE,
  nombre VARCHAR(20) NOT NULL UNIQUE,
  anio_inicio SMALLINT NOT NULL,
  anio_fin SMALLINT NOT NULL,
  activo BOOLEAN NOT NULL DEFAULT true,
  es_actual BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT check_anios CHECK (anio_fin = anio_inicio + 1)
);

CREATE INDEX IF NOT EXISTS idx_ciclos_valor ON public.ciclos_escolares(valor);
CREATE INDEX IF NOT EXISTS idx_ciclos_activo ON public.ciclos_escolares(activo);
CREATE INDEX IF NOT EXISTS idx_ciclos_actual ON public.ciclos_escolares(es_actual);

DROP TRIGGER IF EXISTS trigger_update_ciclo_escolar_timestamp ON public.ciclos_escolares;
CREATE TRIGGER trigger_update_ciclo_escolar_timestamp
  BEFORE UPDATE ON public.ciclos_escolares
  FOR EACH ROW EXECUTE FUNCTION update_ciclo_escolar_updated_at();

DROP TRIGGER IF EXISTS trigger_un_ciclo_actual ON public.ciclos_escolares;
CREATE TRIGGER trigger_un_ciclo_actual
  AFTER INSERT OR UPDATE OF es_actual ON public.ciclos_escolares
  FOR EACH ROW WHEN (NEW.es_actual = true)
  EXECUTE FUNCTION asegurar_un_ciclo_actual();

CREATE TABLE IF NOT EXISTS public.concepto_beca (
  beca_id SMALLINT PRIMARY KEY,
  beca_clase VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.concepto_boucher (
  concepto_id SMALLINT PRIMARY KEY,
  concepto_no CHAR(2) NOT NULL,
  concepto_clase VARCHAR(100) NOT NULL,
  alumno_nivel SMALLINT NOT NULL DEFAULT 0,
  concepto_tipo SMALLINT NOT NULL,
  concepto_descuento SMALLINT NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS concepto_boucher_concepto_no_unique ON public.concepto_boucher (concepto_no);

CREATE TABLE IF NOT EXISTS public.concepto_interno (
  concepto_id SMALLINT PRIMARY KEY,
  concepto_clase VARCHAR(30),
  visible SMALLINT NOT NULL DEFAULT 1,
  orden_visible SMALLINT NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS concepto_interno_visible ON public.concepto_interno (visible);

CREATE TABLE IF NOT EXISTS public.concepto_desayunos (
  id SERIAL PRIMARY KEY,
  desayuno_nombre VARCHAR(100) NOT NULL,
  desayuno_abreviatura VARCHAR(20),
  costo NUMERIC(10, 2) NOT NULL DEFAULT 0
);

-- === Alumnos ===
CREATE TABLE IF NOT EXISTS public.alumno (
  alumno_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alumno_ref INTEGER NULL,
  alumno_app VARCHAR(50) NULL,
  alumno_apm VARCHAR(50) NULL,
  alumno_nombre VARCHAR(50) NULL,
  alumno_nivel SMALLINT NULL,
  alumno_grado SMALLINT NULL,
  alumno_grupo SMALLINT NULL,
  alumno_status SMALLINT NOT NULL,
  alumno_nuevo_ingreso SMALLINT NOT NULL,
  alumno_ciclo_escolar SMALLINT NULL,
  alumno_registro DATE NULL,
  alumno_alta DATE NULL,
  alumno_actualizacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  alumno_boleta SMALLINT NOT NULL,
  mes SMALLINT NOT NULL,
  secret_key VARCHAR(64) NOT NULL,
  motivo VARCHAR(200) NOT NULL,
  responsable VARCHAR(50) NOT NULL,
  estatus_key SMALLINT NOT NULL DEFAULT 0,
  digito INTEGER NOT NULL,
  hijo SMALLINT NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS alumno_ref ON public.alumno (alumno_ref);

DROP TRIGGER IF EXISTS trg_alumno_actualizacion ON public.alumno;
CREATE TRIGGER trg_alumno_actualizacion
  BEFORE UPDATE ON public.alumno
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_timestamp();

CREATE TABLE IF NOT EXISTS public.alumno_detalles (
  detalle_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alumno_id INTEGER NULL,
  alumno_clave VARCHAR(20) NULL,
  alumno_fecha_nac DATE NULL,
  alumno_lugar_nac VARCHAR(50) NULL,
  alumno_curp VARCHAR(18) NULL,
  alumno_sexo CHAR(1) NULL,
  alumno_calle VARCHAR(100) NULL,
  alumno_numero VARCHAR(50) NULL,
  alumno_numeroint VARCHAR(50) NULL,
  alumno_colonia VARCHAR(100) NULL,
  alumno_cp INTEGER NULL,
  alumno_entre_calles VARCHAR(150) NULL,
  estado_id VARCHAR(200) NULL,
  cuidad_id VARCHAR(200) NULL,
  alumno_escuela_procedente VARCHAR(50) NULL,
  tipo_relacion INTEGER NULL,
  comentario_relacion VARCHAR(100) NULL,
  detalle_registro TIMESTAMP NULL,
  detalle_actualizacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS alumno_detalles_alumno_id ON public.alumno_detalles (alumno_id);

DROP TRIGGER IF EXISTS trg_alumno_detalles_actualizacion ON public.alumno_detalles;
CREATE TRIGGER trg_alumno_detalles_actualizacion
  BEFORE UPDATE ON public.alumno_detalles
  FOR EACH ROW EXECUTE FUNCTION public.set_detalle_updated_at_timestamp();

CREATE TABLE IF NOT EXISTS public.alumno_familiar (
  familiar_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alumno_id INTEGER NULL,
  tutor_id SMALLINT NULL,
  familiar_app VARCHAR(50) NULL,
  familiar_apm VARCHAR(50) NULL,
  familiar_nombre VARCHAR(50) NULL,
  familiar_tel VARCHAR(20) NULL,
  familiar_cel VARCHAR(20) NULL,
  familiar_email VARCHAR(100) NULL,
  familiar_recibir_email SMALLINT NOT NULL,
  familiar_fecha_nac DATE NULL,
  familiar_lugar_nac VARCHAR(50) NULL,
  familiar_curp VARCHAR(18) NULL,
  familiar_escolaridad VARCHAR(50) NULL,
  familiar_empresa_nombre VARCHAR(100) NULL,
  familiar_empresa_direccion VARCHAR(200) NULL,
  familiar_empresa_puesto VARCHAR(100) NULL,
  familiar_empresa_tel VARCHAR(20) NULL,
  familiar_vive SMALLINT NOT NULL,
  familiar_registro DATE NULL,
  familiar_actualizacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  familiar_rfc VARCHAR(13) NULL,
  familiar_factura SMALLINT NOT NULL
);

CREATE INDEX IF NOT EXISTS alumno_familiar_tutor_id ON public.alumno_familiar (tutor_id);
CREATE INDEX IF NOT EXISTS alumno_familiar_alumno_id ON public.alumno_familiar (alumno_id);

DROP TRIGGER IF EXISTS trg_alumno_familiar_actualizacion ON public.alumno_familiar;
CREATE TRIGGER trg_alumno_familiar_actualizacion
  BEFORE UPDATE ON public.alumno_familiar
  FOR EACH ROW EXECUTE FUNCTION public.set_familiar_updated_at_timestamp();

CREATE TABLE IF NOT EXISTS public.alumno_contacto (
  contacto_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alumno_id INTEGER NOT NULL,
  tutor_id SMALLINT NULL,
  tutor_clase VARCHAR(30) NULL,
  contacto_tipo SMALLINT NOT NULL,
  contacto_nombre VARCHAR(100) NULL,
  contacto_tel VARCHAR(20) NULL,
  contacto_cel VARCHAR(50) NULL,
  contacto_alta TIMESTAMP NULL,
  contacto_actualizacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS alumno_contacto_alumno_id ON public.alumno_contacto (alumno_id);
CREATE INDEX IF NOT EXISTS alumno_contacto_alumno_tipo ON public.alumno_contacto (alumno_id, contacto_tipo);

DROP TRIGGER IF EXISTS trg_alumno_contacto_actualizacion ON public.alumno_contacto;
CREATE TRIGGER trg_alumno_contacto_actualizacion
  BEFORE UPDATE ON public.alumno_contacto
  FOR EACH ROW EXECUTE FUNCTION public.set_contacto_updated_at_timestamp();

CREATE TABLE IF NOT EXISTS public.alumno_beca (
  alumno_beca_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alumno_id INTEGER NOT NULL,
  beca_id SMALLINT NOT NULL,
  beca_porcentaje SMALLINT NOT NULL,
  beca_estatus SMALLINT NOT NULL,
  beca_ciclo_escolar SMALLINT NOT NULL,
  beca_registro TIMESTAMP NOT NULL,
  beca_actualizacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  beca_p VARCHAR(7) NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS alumno_beca_alumno_id_unique ON public.alumno_beca (alumno_id);
CREATE INDEX IF NOT EXISTS alumno_beca_alumno_id ON public.alumno_beca (alumno_id);
CREATE INDEX IF NOT EXISTS alumno_beca_beca_id ON public.alumno_beca (beca_id);
CREATE INDEX IF NOT EXISTS alumno_beca_ciclo ON public.alumno_beca (beca_ciclo_escolar);

DROP TRIGGER IF EXISTS trg_alumno_beca_actualizacion ON public.alumno_beca;
CREATE TRIGGER trg_alumno_beca_actualizacion
  BEFORE UPDATE ON public.alumno_beca
  FOR EACH ROW EXECUTE FUNCTION public.set_beca_updated_at_timestamp();

-- === Precios ===
CREATE TABLE IF NOT EXISTS public.pago_boucher_precio (
  precio_id INTEGER PRIMARY KEY,
  alumno_nivel SMALLINT NOT NULL,
  precio_inscripcion NUMERIC(10, 2) NOT NULL DEFAULT 0,
  precio_material NUMERIC(10, 2) NOT NULL DEFAULT 0,
  precio_seguro NUMERIC(10, 2) NOT NULL DEFAULT 0,
  precio_cuota_padres NUMERIC(10, 2) NOT NULL DEFAULT 0,
  precio_agosto NUMERIC(10, 2) NOT NULL DEFAULT 0,
  precio_colegiatura NUMERIC(10, 2) NOT NULL DEFAULT 0,
  precio_colegiatura2 NUMERIC(10, 2) NOT NULL DEFAULT 0,
  precio_cambridge NUMERIC(10, 2) NOT NULL DEFAULT 0,
  precio_dtitulacion NUMERIC(10, 2) NOT NULL DEFAULT 0,
  descuento_cambio_nivel SMALLINT NOT NULL DEFAULT 0,
  descuento_cambio_grado SMALLINT NOT NULL DEFAULT 0,
  precio_ciclo_escolar SMALLINT NOT NULL
);

CREATE INDEX IF NOT EXISTS pago_boucher_precio_ciclo_nivel
  ON public.pago_boucher_precio (precio_ciclo_escolar, alumno_nivel);

CREATE TABLE IF NOT EXISTS public.pago_interno_precio (
  precio_interno_id INTEGER PRIMARY KEY,
  alumno_nivel SMALLINT NOT NULL,
  alumno_grado SMALLINT NOT NULL,
  concepto_id SMALLINT NOT NULL,
  precio_interno NUMERIC(6, 2) NOT NULL,
  precio_ciclo_escolar INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS pago_interno_precio_concepto ON public.pago_interno_precio (concepto_id);
CREATE INDEX IF NOT EXISTS pago_interno_precio_ciclo ON public.pago_interno_precio (precio_ciclo_escolar);
CREATE INDEX IF NOT EXISTS pago_interno_precio_lookup ON public.pago_interno_precio (
  concepto_id, precio_ciclo_escolar, alumno_nivel, alumno_grado
);

-- === Boletas ===
CREATE TABLE IF NOT EXISTS public.boleta_materia (
  materia_id INTEGER PRIMARY KEY,
  materia_nombre VARCHAR(120) NOT NULL,
  materia_nivel SMALLINT NOT NULL,
  materia_grado SMALLINT NOT NULL,
  materia_orden SMALLINT NOT NULL DEFAULT 0,
  materia_registro DATE
);

CREATE TABLE IF NOT EXISTS public.boleta_maestro (
  maestro_id INTEGER PRIMARY KEY,
  maestro_app VARCHAR(80),
  maestro_apm VARCHAR(80),
  maestro_nombre VARCHAR(80),
  maestro_usuario VARCHAR(40),
  maestro_clave VARCHAR(80),
  maestro_sexo SMALLINT NOT NULL DEFAULT 0,
  maestro_celular VARCHAR(20),
  maestro_registro DATE,
  maestro_email VARCHAR(120)
);

CREATE TABLE IF NOT EXISTS public.boleta_maestro_grupo (
  grupo_id INTEGER PRIMARY KEY,
  maestro_id INTEGER NOT NULL,
  materia_id INTEGER NOT NULL,
  grupo_letra VARCHAR(10),
  grupo_registro DATE
);

CREATE INDEX IF NOT EXISTS boleta_materia_nivel ON public.boleta_materia (materia_nivel, materia_grado);
CREATE INDEX IF NOT EXISTS boleta_maestro_grupo_maestro ON public.boleta_maestro_grupo (maestro_id);
CREATE INDEX IF NOT EXISTS boleta_maestro_grupo_materia ON public.boleta_maestro_grupo (materia_id);

-- === Pagos ===
CREATE TABLE IF NOT EXISTS public.pago_detalle (
  pago_id INTEGER PRIMARY KEY,
  alumno_id INTEGER,
  pago_nombre VARCHAR(100),
  pago_referencia CHAR(12),
  pago_importe NUMERIC(7, 2) NOT NULL,
  pago_recargo NUMERIC(6, 2) NOT NULL DEFAULT 0,
  pago_forma VARCHAR(30),
  pago_folio VARCHAR(25),
  pago_fecha DATE,
  pago_hora VARCHAR(15),
  pago_emisora VARCHAR(10),
  pago_cancelado SMALLINT NOT NULL DEFAULT 0,
  pago_registro TIMESTAMP,
  pago_actualizacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  facturo VARCHAR(2) NOT NULL DEFAULT '',
  fact VARCHAR(2) NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS pago_detalle_alumno_id ON public.pago_detalle (alumno_id);
CREATE INDEX IF NOT EXISTS pago_detalle_referencia ON public.pago_detalle (pago_referencia);
CREATE INDEX IF NOT EXISTS pago_detalle_fecha ON public.pago_detalle (pago_fecha);

DROP TRIGGER IF EXISTS trg_pago_detalle_actualizacion ON public.pago_detalle;
CREATE TRIGGER trg_pago_detalle_actualizacion
  BEFORE UPDATE ON public.pago_detalle
  FOR EACH ROW EXECUTE FUNCTION public.set_pago_detalle_actualizacion_timestamp();

CREATE TABLE IF NOT EXISTS public.pago_interno (
  pago_id INTEGER PRIMARY KEY,
  alumno_id INTEGER,
  concepto_id SMALLINT NOT NULL,
  concepto_otro VARCHAR(50),
  pago_folio INTEGER NOT NULL,
  pago_importe NUMERIC(6, 2) NOT NULL,
  pago_fecha DATE,
  pago_cancelado SMALLINT NOT NULL DEFAULT 0,
  pago_ciclo_escolar SMALLINT,
  pago_registro TIMESTAMP,
  pago_actualizacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS pago_interno_alumno_id ON public.pago_interno (alumno_id);
CREATE INDEX IF NOT EXISTS pago_interno_concepto_id ON public.pago_interno (concepto_id);
CREATE INDEX IF NOT EXISTS pago_interno_ciclo ON public.pago_interno (pago_ciclo_escolar);
CREATE INDEX IF NOT EXISTS pago_interno_folio ON public.pago_interno (pago_folio);

DROP TRIGGER IF EXISTS trg_pago_interno_actualizacion ON public.pago_interno;
CREATE TRIGGER trg_pago_interno_actualizacion
  BEFORE UPDATE ON public.pago_interno
  FOR EACH ROW EXECUTE FUNCTION public.set_pago_interno_actualizacion_timestamp();

CREATE TABLE IF NOT EXISTS public.pago_prorroga (
  prorroga_id INTEGER PRIMARY KEY,
  alumno_id INTEGER NOT NULL,
  prorroga_fecha DATE NOT NULL,
  correccion SMALLINT NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS pago_prorroga_alumno ON public.pago_prorroga (alumno_id);
CREATE INDEX IF NOT EXISTS pago_prorroga_fecha ON public.pago_prorroga (prorroga_fecha);

-- === Desayunos ===
CREATE TABLE IF NOT EXISTS public.personal (
  id SERIAL PRIMARY KEY,
  personal_nombre VARCHAR(100),
  personal_app VARCHAR(50),
  personal_apm VARCHAR(50),
  personal_nombre_completo VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS public.pago_desayunos (
  id BIGSERIAL PRIMARY KEY,
  pago_ref VARCHAR(50) NOT NULL,
  pago_descripcion VARCHAR(200),
  pago_costo NUMERIC(10, 2),
  pago_fecha DATE,
  pago_cantidad INTEGER DEFAULT 1,
  pago_orden BIGINT,
  pago_estatus SMALLINT DEFAULT 1
);

CREATE INDEX IF NOT EXISTS pago_desayunos_fecha ON public.pago_desayunos (pago_fecha);
CREATE INDEX IF NOT EXISTS pago_desayunos_ref ON public.pago_desayunos (pago_ref);

-- === Sistema ===
CREATE TABLE IF NOT EXISTS public.usuario (
  usuario_id SMALLSERIAL PRIMARY KEY,
  perfil_id SMALLINT,
  usuario_app VARCHAR(50),
  usuario_apm VARCHAR(50),
  usuario_nombre VARCHAR(50),
  usuario_username VARCHAR(20) NOT NULL,
  usuario_email VARCHAR(100),
  usuario_password VARCHAR(255) NOT NULL,
  usuario_status SMALLINT,
  usuario_alta TIMESTAMP,
  nivel INTEGER DEFAULT 1
);

-- === Banorte / OpenPay ===
CREATE TABLE IF NOT EXISTS public.banorte_pago_pendiente (
  referencia TEXT PRIMARY KEY,
  monto NUMERIC(12, 2) NOT NULL,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS banorte_pago_pendiente_creado_en_idx
  ON public.banorte_pago_pendiente (creado_en DESC);

CREATE TABLE IF NOT EXISTS public.banorte_payw_intento (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  referencia TEXT NOT NULL,
  importe NUMERIC(12, 2),
  payw_result TEXT,
  payw_code TEXT,
  auth_result TEXT,
  auth_code TEXT,
  mensaje_es TEXT NOT NULL,
  mensaje_raw TEXT,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS banorte_payw_intento_referencia_idx
  ON public.banorte_payw_intento (referencia, creado_en DESC);

CREATE TABLE IF NOT EXISTS public.openpay_webhook_verificacion (
  id BIGSERIAL PRIMARY KEY,
  cuenta VARCHAR(20) NOT NULL,
  verification_code VARCHAR(64) NOT NULL,
  recibido_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS openpay_webhook_verificacion_cuenta_fecha
  ON public.openpay_webhook_verificacion (cuenta, recibido_en DESC);

CREATE TABLE IF NOT EXISTS public.openpay_webhook_log (
  id BIGSERIAL PRIMARY KEY,
  cuenta VARCHAR(20) NOT NULL,
  tipo_evento VARCHAR(64) NOT NULL,
  referencia VARCHAR(20),
  transaction_id VARCHAR(80),
  ok BOOLEAN NOT NULL DEFAULT true,
  mensaje TEXT,
  payload JSONB,
  recibido_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS openpay_webhook_log_cuenta_fecha
  ON public.openpay_webhook_log (cuenta, recibido_en DESC);

-- === Salida a pie (portal) ===
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN NEW.updated_at = NOW(); RETURN NEW; END;
$$ LANGUAGE plpgsql;

CREATE TABLE IF NOT EXISTS public.registro_salida_pie (
  id BIGSERIAL PRIMARY KEY,
  alumno_ref TEXT NOT NULL,
  tipo_registro TEXT NOT NULL CHECK (tipo_registro IN ('permanente', 'eventual')),
  dias_semana TEXT[],
  fechas_especificas DATE[],
  cancelaciones_usadas INT DEFAULT 0,
  activo BOOLEAN DEFAULT TRUE,
  nombre_tutor TEXT NOT NULL,
  email_tutor TEXT NOT NULL,
  telefono_tutor TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT max_5_dias CHECK (
    (tipo_registro = 'eventual') OR
    (tipo_registro = 'permanente' AND array_length(dias_semana, 1) <= 5)
  ),
  CONSTRAINT max_5_cancelaciones CHECK (
    (tipo_registro = 'eventual') OR
    (tipo_registro = 'permanente' AND cancelaciones_usadas <= 5)
  )
);

CREATE INDEX IF NOT EXISTS idx_registro_salida_pie_alumno_ref ON public.registro_salida_pie(alumno_ref);
CREATE INDEX IF NOT EXISTS idx_registro_salida_pie_activo ON public.registro_salida_pie(activo);
CREATE INDEX IF NOT EXISTS idx_registro_salida_pie_tipo ON public.registro_salida_pie(tipo_registro);

CREATE UNIQUE INDEX IF NOT EXISTS idx_registro_salida_pie_permanente_unico
  ON public.registro_salida_pie(alumno_ref)
  WHERE tipo_registro = 'permanente' AND activo = TRUE;

DROP TRIGGER IF EXISTS update_registro_salida_pie_updated_at ON public.registro_salida_pie;
CREATE TRIGGER update_registro_salida_pie_updated_at
  BEFORE UPDATE ON public.registro_salida_pie
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- === Foreign keys ===
ALTER TABLE public.alumno_detalles DROP CONSTRAINT IF EXISTS alumno_detalles_alumno_id_fkey;
ALTER TABLE public.alumno_detalles
  ADD CONSTRAINT alumno_detalles_alumno_id_fkey
  FOREIGN KEY (alumno_id) REFERENCES public.alumno (alumno_id)
  ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE public.alumno_familiar DROP CONSTRAINT IF EXISTS alumno_familiar_alumno_id_fkey;
ALTER TABLE public.alumno_familiar
  ADD CONSTRAINT alumno_familiar_alumno_id_fkey
  FOREIGN KEY (alumno_id) REFERENCES public.alumno (alumno_id)
  ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE public.alumno_contacto DROP CONSTRAINT IF EXISTS alumno_contacto_alumno_id_fkey;
ALTER TABLE public.alumno_contacto
  ADD CONSTRAINT alumno_contacto_alumno_id_fkey
  FOREIGN KEY (alumno_id) REFERENCES public.alumno (alumno_id)
  ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE public.alumno_beca DROP CONSTRAINT IF EXISTS alumno_beca_alumno_id_fkey;
ALTER TABLE public.alumno_beca
  ADD CONSTRAINT alumno_beca_alumno_id_fkey
  FOREIGN KEY (alumno_id) REFERENCES public.alumno (alumno_id)
  ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE public.alumno_beca DROP CONSTRAINT IF EXISTS alumno_beca_beca_id_fkey;
ALTER TABLE public.alumno_beca
  ADD CONSTRAINT alumno_beca_beca_id_fkey
  FOREIGN KEY (beca_id) REFERENCES public.concepto_beca (beca_id)
  ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE public.pago_interno_precio DROP CONSTRAINT IF EXISTS pago_interno_precio_concepto_id_fkey;
ALTER TABLE public.pago_interno_precio
  ADD CONSTRAINT pago_interno_precio_concepto_id_fkey
  FOREIGN KEY (concepto_id) REFERENCES public.concepto_interno (concepto_id)
  ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE public.boleta_maestro_grupo DROP CONSTRAINT IF EXISTS boleta_maestro_grupo_maestro_id_fkey;
ALTER TABLE public.boleta_maestro_grupo
  ADD CONSTRAINT boleta_maestro_grupo_maestro_id_fkey
  FOREIGN KEY (maestro_id) REFERENCES public.boleta_maestro (maestro_id) ON DELETE CASCADE;

ALTER TABLE public.boleta_maestro_grupo DROP CONSTRAINT IF EXISTS boleta_maestro_grupo_materia_id_fkey;
ALTER TABLE public.boleta_maestro_grupo
  ADD CONSTRAINT boleta_maestro_grupo_materia_id_fkey
  FOREIGN KEY (materia_id) REFERENCES public.boleta_materia (materia_id) ON DELETE CASCADE;

ALTER TABLE public.pago_detalle DROP CONSTRAINT IF EXISTS pago_detalle_alumno_id_fkey;
ALTER TABLE public.pago_detalle
  ADD CONSTRAINT pago_detalle_alumno_id_fkey
  FOREIGN KEY (alumno_id) REFERENCES public.alumno (alumno_id)
  ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE public.pago_interno DROP CONSTRAINT IF EXISTS pago_interno_alumno_id_fkey;
ALTER TABLE public.pago_interno
  ADD CONSTRAINT pago_interno_alumno_id_fkey
  FOREIGN KEY (alumno_id) REFERENCES public.alumno (alumno_id)
  ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE public.pago_interno DROP CONSTRAINT IF EXISTS pago_interno_concepto_id_fkey;
ALTER TABLE public.pago_interno
  ADD CONSTRAINT pago_interno_concepto_id_fkey
  FOREIGN KEY (concepto_id) REFERENCES public.concepto_interno (concepto_id)
  ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE public.pago_prorroga DROP CONSTRAINT IF EXISTS pago_prorroga_alumno_id_fkey;
ALTER TABLE public.pago_prorroga
  ADD CONSTRAINT pago_prorroga_alumno_id_fkey
  FOREIGN KEY (alumno_id) REFERENCES public.alumno (alumno_id)
  ON DELETE RESTRICT ON UPDATE CASCADE;
