-- Ficha médica del alumno (portal de inscripciones / admisiones legacy).
CREATE TABLE IF NOT EXISTS public.alumno_dato_medico (
  dato_medico_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alumno_id INTEGER NOT NULL,
  alumno_peso VARCHAR(30) NULL,
  alumno_estatura VARCHAR(30) NULL,
  alumno_sangre_tipo VARCHAR(30) NULL,
  alumno_alergia VARCHAR(250) NULL,
  alumno_padecimiento VARCHAR(200) NULL,
  alumno_medicina VARCHAR(200) NULL,
  alumno_suministrar VARCHAR(200) NULL,
  alumno_medicamentos VARCHAR(200) NULL,
  alumno_atencion_interna SMALLINT NULL,
  alumno_afiliacion VARCHAR(50) NULL,
  alumno_afiliacion_externa VARCHAR(100) NULL,
  alumno_servicio_medico SMALLINT NULL,
  dato_medico_actualizacion DATE NULL,
  dato_medico_registro TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS alumno_dato_medico_alumno_id
  ON public.alumno_dato_medico (alumno_id);

ALTER TABLE public.alumno_dato_medico
  DROP CONSTRAINT IF EXISTS alumno_dato_medico_alumno_id_fkey;

ALTER TABLE public.alumno_dato_medico
  ADD CONSTRAINT alumno_dato_medico_alumno_id_fkey
  FOREIGN KEY (alumno_id) REFERENCES public.alumno (alumno_id) ON DELETE CASCADE;
