-- Reportes académicos y de conducta (secundaria). Paridad legacy secundaria_2.0.
-- Catálogos boleta_materia / boleta_maestro / boleta_maestro_grupo ya existen en Winston Servicios.

CREATE TABLE IF NOT EXISTS public.reporte_escolar (
  reporte_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alumno_id INTEGER NOT NULL REFERENCES public.alumno (alumno_id),
  materia_id INTEGER NULL REFERENCES public.boleta_materia (materia_id),
  perfil_id SMALLINT NOT NULL,
  usuario_id INTEGER NOT NULL,
  reporte_tipo SMALLINT NOT NULL,
  reporte_motivo SMALLINT NOT NULL DEFAULT 0,
  reporte_no SMALLINT NOT NULL DEFAULT 0,
  reporte_mensaje TEXT NOT NULL DEFAULT '',
  reporte_status SMALLINT NOT NULL DEFAULT 1,
  reporte_ciclo SMALLINT NOT NULL DEFAULT 0,
  reporte_ciclo_escolar SMALLINT NOT NULL,
  reporte_mdv VARCHAR(64) NOT NULL,
  reporte_enviado SMALLINT NOT NULL DEFAULT 0,
  reporte_confirmado SMALLINT NOT NULL DEFAULT 0,
  reporte_registro TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS reporte_escolar_mdv_uidx ON public.reporte_escolar (reporte_mdv);
CREATE INDEX IF NOT EXISTS reporte_escolar_alumno_idx ON public.reporte_escolar (alumno_id, reporte_ciclo_escolar, reporte_tipo);
CREATE INDEX IF NOT EXISTS reporte_escolar_inbox_idx ON public.reporte_escolar (reporte_ciclo_escolar, reporte_confirmado, reporte_status, reporte_tipo);

CREATE TABLE IF NOT EXISTS public.reporte_cita (
  cita_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alumno_id INTEGER NOT NULL REFERENCES public.alumno (alumno_id),
  materia_id INTEGER NULL REFERENCES public.boleta_materia (materia_id),
  perfil_id SMALLINT NOT NULL,
  usuario_id INTEGER NOT NULL,
  cita_tipo SMALLINT NOT NULL,
  cita_mensaje TEXT NOT NULL DEFAULT '',
  cita_status SMALLINT NOT NULL DEFAULT 1,
  cita_ciclo_escolar SMALLINT NOT NULL,
  cita_mdv VARCHAR(64) NOT NULL,
  cita_fecha TIMESTAMPTZ NULL,
  cita_enviada SMALLINT NOT NULL DEFAULT 0,
  cita_confirmada SMALLINT NOT NULL DEFAULT 0,
  cita_registro TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS reporte_cita_mdv_idx ON public.reporte_cita (cita_mdv);
CREATE INDEX IF NOT EXISTS reporte_cita_ciclo_idx ON public.reporte_cita (cita_ciclo_escolar, cita_status);

CREATE TABLE IF NOT EXISTS public.reporte_suspension (
  suspension_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alumno_id INTEGER NOT NULL REFERENCES public.alumno (alumno_id),
  reporte_id INTEGER NOT NULL REFERENCES public.reporte_escolar (reporte_id),
  suspension_ciclo_escolar SMALLINT NOT NULL,
  suspension_fecha DATE NULL,
  suspension_enviada SMALLINT NOT NULL DEFAULT 0,
  suspension_registro TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS reporte_suspension_ciclo_idx ON public.reporte_suspension (suspension_ciclo_escolar);

ALTER TABLE public.reporte_escolar ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reporte_escolar FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS servicios_insforge_deny_anon ON public.reporte_escolar;
CREATE POLICY servicios_insforge_deny_anon ON public.reporte_escolar
  FOR ALL TO anon, authenticated USING (false) WITH CHECK (false);
REVOKE ALL ON public.reporte_escolar FROM anon, authenticated;

ALTER TABLE public.reporte_cita ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reporte_cita FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS servicios_insforge_deny_anon ON public.reporte_cita;
CREATE POLICY servicios_insforge_deny_anon ON public.reporte_cita
  FOR ALL TO anon, authenticated USING (false) WITH CHECK (false);
REVOKE ALL ON public.reporte_cita FROM anon, authenticated;

ALTER TABLE public.reporte_suspension ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reporte_suspension FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS servicios_insforge_deny_anon ON public.reporte_suspension;
CREATE POLICY servicios_insforge_deny_anon ON public.reporte_suspension
  FOR ALL TO anon, authenticated USING (false) WITH CHECK (false);
REVOKE ALL ON public.reporte_suspension FROM anon, authenticated;
