-- Situación delicada: número de control (alumno_ref) antes de alumno_id.

CREATE TABLE public.alumno_situacion_delicada_ref (
  situacion_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alumno_ref integer NOT NULL,
  alumno_id integer NOT NULL REFERENCES public.alumno (alumno_id) ON DELETE CASCADE,
  no_corresponde boolean NOT NULL DEFAULT true,
  comentarios text NOT NULL DEFAULT '',
  actualizado_por text NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT alumno_situacion_delicada_ref_alumno_ref_key UNIQUE (alumno_ref),
  CONSTRAINT alumno_situacion_delicada_ref_alumno_id_key UNIQUE (alumno_id)
);

INSERT INTO public.alumno_situacion_delicada_ref (
  alumno_ref,
  alumno_id,
  no_corresponde,
  comentarios,
  actualizado_por,
  created_at,
  updated_at
)
SELECT
  a.alumno_ref,
  s.alumno_id,
  s.no_corresponde,
  s.comentarios,
  s.actualizado_por,
  s.created_at,
  s.updated_at
FROM public.alumno_situacion_delicada s
JOIN public.alumno a ON a.alumno_id = s.alumno_id
WHERE a.alumno_ref IS NOT NULL;

DROP TABLE public.alumno_situacion_delicada;

ALTER TABLE public.alumno_situacion_delicada_ref
  RENAME TO alumno_situacion_delicada;

ALTER TABLE public.alumno_situacion_delicada
  RENAME CONSTRAINT alumno_situacion_delicada_ref_alumno_ref_key
  TO alumno_situacion_delicada_alumno_ref_key;

ALTER TABLE public.alumno_situacion_delicada
  RENAME CONSTRAINT alumno_situacion_delicada_ref_alumno_id_key
  TO alumno_situacion_delicada_alumno_id_key;

COMMENT ON TABLE public.alumno_situacion_delicada IS
  'Situación delicada en ficha del alumno. alumno_ref (no. de control) y alumno_id. no_corresponde = sin caso.';

CREATE INDEX IF NOT EXISTS alumno_situacion_delicada_caso_idx
  ON public.alumno_situacion_delicada (alumno_ref)
  WHERE no_corresponde = false;

DROP TRIGGER IF EXISTS alumno_situacion_delicada_updated_at ON public.alumno_situacion_delicada;
CREATE TRIGGER alumno_situacion_delicada_updated_at
  BEFORE UPDATE ON public.alumno_situacion_delicada
  FOR EACH ROW
  EXECUTE FUNCTION system.update_updated_at();

ALTER TABLE public.alumno_situacion_delicada ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.alumno_situacion_delicada FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS servicios_insforge_deny_anon ON public.alumno_situacion_delicada;
CREATE POLICY servicios_insforge_deny_anon ON public.alumno_situacion_delicada
  FOR ALL TO anon, authenticated USING (false) WITH CHECK (false);
REVOKE ALL ON public.alumno_situacion_delicada FROM anon, authenticated;
