-- Seed catálogo boletas desde data/boletas/*.csv
BEGIN;
-- Catálogo (reemplazo completo)
DELETE FROM boleta_maestro_grupo;
DELETE FROM boleta_maestro;
DELETE FROM boleta_materia;
INSERT INTO boleta_materia (materia_id, materia_nombre, materia_nivel, materia_grado, materia_orden, materia_registro) VALUES (1, 'ESPAÑOL I (LENGUA MATERNA)', 4, 1, 1, '2017-02-10');
INSERT INTO boleta_materia (materia_id, materia_nombre, materia_nivel, materia_grado, materia_orden, materia_registro) VALUES (2, 'ESPAÑOL II', 4, 2, 1, '2017-02-10');
INSERT INTO boleta_materia (materia_id, materia_nombre, materia_nivel, materia_grado, materia_orden, materia_registro) VALUES (3, 'ESPAÑOL III', 4, 3, 1, '2017-02-10');
INSERT INTO boleta_materia (materia_id, materia_nombre, materia_nivel, materia_grado, materia_orden, materia_registro) VALUES (4, 'MATEMÁTICAS I', 4, 1, 4, '2017-02-10');
INSERT INTO boleta_materia (materia_id, materia_nombre, materia_nivel, materia_grado, materia_orden, materia_registro) VALUES (5, 'MATEMÁTICAS II', 4, 2, 4, '2017-02-10');
INSERT INTO boleta_materia (materia_id, materia_nombre, materia_nivel, materia_grado, materia_orden, materia_registro) VALUES (6, 'MATEMÁTICAS III', 4, 3, 4, '2017-02-10');
INSERT INTO boleta_materia (materia_id, materia_nombre, materia_nivel, materia_grado, materia_orden, materia_registro) VALUES (7, 'CIENCIAS (BIOLOGÍA)', 4, 1, 5, '2017-02-10');
INSERT INTO boleta_materia (materia_id, materia_nombre, materia_nivel, materia_grado, materia_orden, materia_registro) VALUES (9, 'CIENCIAS III (ÉNFASIS EN QUÍMICA)', 4, 3, 5, '2017-02-10');
INSERT INTO boleta_materia (materia_id, materia_nombre, materia_nivel, materia_grado, materia_orden, materia_registro) VALUES (10, 'ARTES I', 4, 1, 3, '2017-02-10');
INSERT INTO boleta_materia (materia_id, materia_nombre, materia_nivel, materia_grado, materia_orden, materia_registro) VALUES (11, 'ARTES II', 4, 2, 3, '2017-02-10');
INSERT INTO boleta_materia (materia_id, materia_nombre, materia_nivel, materia_grado, materia_orden, materia_registro) VALUES (12, 'ARTES III', 4, 3, 3, '2017-02-10');
INSERT INTO boleta_materia (materia_id, materia_nombre, materia_nivel, materia_grado, materia_orden, materia_registro) VALUES (13, 'FORMACIÓN SOCIAL Y HUMANA I', 4, 1, 14, '2017-02-10');
INSERT INTO boleta_materia (materia_id, materia_nombre, materia_nivel, materia_grado, materia_orden, materia_registro) VALUES (14, 'FORMACIÓN SOCIAL Y HUMANA II', 4, 2, 14, '2017-02-10');
INSERT INTO boleta_materia (materia_id, materia_nombre, materia_nivel, materia_grado, materia_orden, materia_registro) VALUES (15, 'FORMACIÓN SOCIAL Y HUMANA III', 4, 3, 14, '2017-02-10');
INSERT INTO boleta_materia (materia_id, materia_nombre, materia_nivel, materia_grado, materia_orden, materia_registro) VALUES (16, 'INNOVACIÓN Y TECNOLOGÍA I', 4, 1, 9, '2017-02-10');
INSERT INTO boleta_materia (materia_id, materia_nombre, materia_nivel, materia_grado, materia_orden, materia_registro) VALUES (17, 'INNOVACIÓN Y TECNOLOGÍA II', 4, 2, 8, '2017-02-10');
INSERT INTO boleta_materia (materia_id, materia_nombre, materia_nivel, materia_grado, materia_orden, materia_registro) VALUES (18, 'INNOVACIÓN Y TECNOLOGÍA III', 4, 3, 8, '2017-02-10');
INSERT INTO boleta_materia (materia_id, materia_nombre, materia_nivel, materia_grado, materia_orden, materia_registro) VALUES (19, 'EDUCACIÓN FÍSICA I', 4, 1, 10, '2017-02-10');
INSERT INTO boleta_materia (materia_id, materia_nombre, materia_nivel, materia_grado, materia_orden, materia_registro) VALUES (20, 'EDUCACIÓN FÍSICA II', 4, 2, 9, '2017-02-10');
INSERT INTO boleta_materia (materia_id, materia_nombre, materia_nivel, materia_grado, materia_orden, materia_registro) VALUES (21, 'EDUCACIÓN FÍSICA III', 4, 3, 9, '2017-02-10');
INSERT INTO boleta_materia (materia_id, materia_nombre, materia_nivel, materia_grado, materia_orden, materia_registro) VALUES (22, 'FORMACIÓN CÍVICA Y ÉTICA I', 4, 1, 8, '2017-02-10');
INSERT INTO boleta_materia (materia_id, materia_nombre, materia_nivel, materia_grado, materia_orden, materia_registro) VALUES (23, 'FORMACIÓN CÍVICA Y ÉTICA II', 4, 2, 7, '2017-02-10');
INSERT INTO boleta_materia (materia_id, materia_nombre, materia_nivel, materia_grado, materia_orden, materia_registro) VALUES (24, 'GEOGRAFÍA DE MÉXICO Y EL MUNDO I', 4, 1, 6, '2017-02-10');
INSERT INTO boleta_materia (materia_id, materia_nombre, materia_nivel, materia_grado, materia_orden, materia_registro) VALUES (25, 'HISTORIA I', 4, 1, 7, '2017-02-10');
INSERT INTO boleta_materia (materia_id, materia_nombre, materia_nivel, materia_grado, materia_orden, materia_registro) VALUES (26, 'FORMACIÓN CÍVICA Y ÉTICA III', 4, 3, 7, '2017-02-10');
INSERT INTO boleta_materia (materia_id, materia_nombre, materia_nivel, materia_grado, materia_orden, materia_registro) VALUES (27, 'FRANCÉS I', 4, 1, 13, '2017-02-10');
INSERT INTO boleta_materia (materia_id, materia_nombre, materia_nivel, materia_grado, materia_orden, materia_registro) VALUES (28, 'FRANCÉS II', 4, 2, 13, '2017-02-10');
INSERT INTO boleta_materia (materia_id, materia_nombre, materia_nivel, materia_grado, materia_orden, materia_registro) VALUES (29, 'FRANCÉS III', 4, 3, 13, '2017-02-10');
INSERT INTO boleta_materia (materia_id, materia_nombre, materia_nivel, materia_grado, materia_orden, materia_registro) VALUES (37, 'INGLES 2°', 4, 2, 2, '2017-02-10');
INSERT INTO boleta_materia (materia_id, materia_nombre, materia_nivel, materia_grado, materia_orden, materia_registro) VALUES (38, 'INGLES 3°', 4, 3, 2, '2017-02-10');
INSERT INTO boleta_materia (materia_id, materia_nombre, materia_nivel, materia_grado, materia_orden, materia_registro) VALUES (39, 'HISTORIA II', 4, 2, 6, '2017-02-10');
INSERT INTO boleta_materia (materia_id, materia_nombre, materia_nivel, materia_grado, materia_orden, materia_registro) VALUES (43, 'CIENCIAS II (ÉNFASIS EN FÍSICA)', 4, 2, 5, '2017-02-10');
INSERT INTO boleta_materia (materia_id, materia_nombre, materia_nivel, materia_grado, materia_orden, materia_registro) VALUES (44, 'HISTORIA III', 4, 3, 6, '2018-08-31');
INSERT INTO boleta_materia (materia_id, materia_nombre, materia_nivel, materia_grado, materia_orden, materia_registro) VALUES (45, 'MINDFULNESS I', 4, 1, 11, '2018-10-12');
INSERT INTO boleta_materia (materia_id, materia_nombre, materia_nivel, materia_grado, materia_orden, materia_registro) VALUES (46, 'MINDFULNESS II', 4, 2, 11, '2018-10-12');
INSERT INTO boleta_materia (materia_id, materia_nombre, materia_nivel, materia_grado, materia_orden, materia_registro) VALUES (47, 'MINDFULNESS III', 4, 3, 11, '2018-10-12');
INSERT INTO boleta_materia (materia_id, materia_nombre, materia_nivel, materia_grado, materia_orden, materia_registro) VALUES (48, 'ROBÓTICA I', 4, 1, 12, '2018-10-15');
INSERT INTO boleta_materia (materia_id, materia_nombre, materia_nivel, materia_grado, materia_orden, materia_registro) VALUES (49, 'ROBÓTICA II', 4, 2, 12, '2018-10-15');
INSERT INTO boleta_materia (materia_id, materia_nombre, materia_nivel, materia_grado, materia_orden, materia_registro) VALUES (50, 'ROBÓTICA III', 4, 3, 12, '2018-10-15');
INSERT INTO boleta_materia (materia_id, materia_nombre, materia_nivel, materia_grado, materia_orden, materia_registro) VALUES (52, 'INGLES 1°', 4, 1, 2, '2018-10-24');
INSERT INTO boleta_materia (materia_id, materia_nombre, materia_nivel, materia_grado, materia_orden, materia_registro) VALUES (53, 'EMPRENDIMIENTO I', 4, 1, 15, '2023-09-15');
INSERT INTO boleta_materia (materia_id, materia_nombre, materia_nivel, materia_grado, materia_orden, materia_registro) VALUES (54, 'EMPRENDIMIENTO II', 4, 2, 15, '2023-09-15');
INSERT INTO boleta_materia (materia_id, materia_nombre, materia_nivel, materia_grado, materia_orden, materia_registro) VALUES (55, 'EMPRENDIMIENTO III', 4, 3, 15, '2023-09-15');
INSERT INTO boleta_maestro (maestro_id, maestro_app, maestro_apm, maestro_nombre, maestro_usuario, maestro_clave, maestro_sexo, maestro_celular, maestro_registro, maestro_email) VALUES (6, 'BOLANOS', 'DE LA VEGA', 'MIRNA ALICIA', 'Mirna', 'aB3$fG7*jK9@', 1, NULL, '2016-11-18', 'madmuaselalice@hotmail.com');
INSERT INTO boleta_maestro (maestro_id, maestro_app, maestro_apm, maestro_nombre, maestro_usuario, maestro_clave, maestro_sexo, maestro_celular, maestro_registro, maestro_email) VALUES (8, 'GAMEZ', NULL, 'ELIZABETH', 'eli', 'xY2!zW8*vU5%', 1, NULL, '2023-12-08', NULL);
INSERT INTO boleta_maestro (maestro_id, maestro_app, maestro_apm, maestro_nombre, maestro_usuario, maestro_clave, maestro_sexo, maestro_celular, maestro_registro, maestro_email) VALUES (11, 'REYES', 'VARGAS', 'MEIGHLYNG VEIGELIA', 'Reyes', 'hJ8^kL2#mN6&', 1, NULL, '2016-11-18', 'meighlyng_vargas0784@hotmail.com');
INSERT INTO boleta_maestro (maestro_id, maestro_app, maestro_apm, maestro_nombre, maestro_usuario, maestro_clave, maestro_sexo, maestro_celular, maestro_registro, maestro_email) VALUES (24, 'DEL ANGEL', 'DEL ANGEL', 'RUBISEL', 'ddr1', 'zX5!cV8*bN3%', 0, NULL, '2018-10-26', 'rubiselrdd@gmail.com');
INSERT INTO boleta_maestro (maestro_id, maestro_app, maestro_apm, maestro_nombre, maestro_usuario, maestro_clave, maestro_sexo, maestro_celular, maestro_registro, maestro_email) VALUES (25, 'TREJO', 'COVARRUBIAS', 'NOE', 'noe', 'tR9@yU2&iO6!', 0, NULL, '2020-01-16', 'noe_trejo@hotmail.com');
INSERT INTO boleta_maestro (maestro_id, maestro_app, maestro_apm, maestro_nombre, maestro_usuario, maestro_clave, maestro_sexo, maestro_celular, maestro_registro, maestro_email) VALUES (31, 'LUQUE', 'FLORES', 'ANA MONTSERRATH', 'amfl', 'qW4$eR7%tY2^', 1, NULL, '2022-11-03', NULL);
INSERT INTO boleta_maestro (maestro_id, maestro_app, maestro_apm, maestro_nombre, maestro_usuario, maestro_clave, maestro_sexo, maestro_celular, maestro_registro, maestro_email) VALUES (34, 'PEREZ', 'MORALES', 'JACQUELINE', 'jaqueline', 'lK3#jH6@gF1!', 1, NULL, '2022-09-07', NULL);
INSERT INTO boleta_maestro (maestro_id, maestro_app, maestro_apm, maestro_nombre, maestro_usuario, maestro_clave, maestro_sexo, maestro_celular, maestro_registro, maestro_email) VALUES (37, 'IDIOMAS', NULL, NULL, 'lion', 'vB5%nM8&cX2!', 1, NULL, '2022-09-07', NULL);
INSERT INTO boleta_maestro (maestro_id, maestro_app, maestro_apm, maestro_nombre, maestro_usuario, maestro_clave, maestro_sexo, maestro_celular, maestro_registro, maestro_email) VALUES (40, NULL, NULL, 'YOLANDA', 'yoli', 'pO7!aS3#dF8$', 1, NULL, '2021-04-22', NULL);
INSERT INTO boleta_maestro (maestro_id, maestro_app, maestro_apm, maestro_nombre, maestro_usuario, maestro_clave, maestro_sexo, maestro_celular, maestro_registro, maestro_email) VALUES (41, 'SANCHEZ', 'SANCHEZ', 'MARTHA PATRICIA', 'marta', 'rT6@yU1&iP9!', 1, NULL, '2023-09-15', NULL);
INSERT INTO boleta_maestro (maestro_id, maestro_app, maestro_apm, maestro_nombre, maestro_usuario, maestro_clave, maestro_sexo, maestro_celular, maestro_registro, maestro_email) VALUES (42, 'MALDONADO', 'LARIOS', 'LIZZETH', 'lizz', 'wE5$qR3%tY7^', 1, NULL, '2023-09-15', NULL);
INSERT INTO boleta_maestro (maestro_id, maestro_app, maestro_apm, maestro_nombre, maestro_usuario, maestro_clave, maestro_sexo, maestro_celular, maestro_registro, maestro_email) VALUES (46, 'Amaro', 'Del Ángel', 'Sofia Nayelli', 'sofi', 'aS4!dF7#gH1$', 1, NULL, '2023-12-06', NULL);
INSERT INTO boleta_maestro (maestro_id, maestro_app, maestro_apm, maestro_nombre, maestro_usuario, maestro_clave, maestro_sexo, maestro_celular, maestro_registro, maestro_email) VALUES (47, 'TORRES', NULL, 'IRVING', 'irving', 'yU2@iP8&oI6!', 1, NULL, '2024-09-04', NULL);
INSERT INTO boleta_maestro (maestro_id, maestro_app, maestro_apm, maestro_nombre, maestro_usuario, maestro_clave, maestro_sexo, maestro_celular, maestro_registro, maestro_email) VALUES (49, 'HUERTA', 'RODRIGUEZ', 'LILIAN ALEXIA', 'lilian', 'eR5%tY9^uO3&', 1, NULL, '2024-09-24', NULL);
INSERT INTO boleta_maestro (maestro_id, maestro_app, maestro_apm, maestro_nombre, maestro_usuario, maestro_clave, maestro_sexo, maestro_celular, maestro_registro, maestro_email) VALUES (50, 'CASTILLO', NULL, 'KARLA', 'karla', 'jH6#gF2!dS8$', 1, NULL, '2024-09-04', NULL);
INSERT INTO boleta_maestro (maestro_id, maestro_app, maestro_apm, maestro_nombre, maestro_usuario, maestro_clave, maestro_sexo, maestro_celular, maestro_registro, maestro_email) VALUES (51, 'GAMEZ', NULL, 'MELISSA', 'melissa', 'cX7!zL3@kQ9#', 1, NULL, '2024-09-04', NULL);
INSERT INTO boleta_maestro (maestro_id, maestro_app, maestro_apm, maestro_nombre, maestro_usuario, maestro_clave, maestro_sexo, maestro_celular, maestro_registro, maestro_email) VALUES (52, 'ARADILLAS', NULL, 'XOCHITL', 'xochitl', 'qL8&fR5#wM3%', 1, NULL, '2025-10-01', NULL);
INSERT INTO boleta_maestro (maestro_id, maestro_app, maestro_apm, maestro_nombre, maestro_usuario, maestro_clave, maestro_sexo, maestro_celular, maestro_registro, maestro_email) VALUES (53, 'RAMIREZ', NULL, 'JAVIER', 'javier', 'zC4^bT9!hJ6&', 0, NULL, '2025-10-01', NULL);
INSERT INTO boleta_maestro (maestro_id, maestro_app, maestro_apm, maestro_nombre, maestro_usuario, maestro_clave, maestro_sexo, maestro_celular, maestro_registro, maestro_email) VALUES (54, 'PALOMO', NULL, 'ANYELA', 'anyela', 'mV7$fK2*jN8#', 1, NULL, NULL, NULL);
INSERT INTO boleta_maestro (maestro_id, maestro_app, maestro_apm, maestro_nombre, maestro_usuario, maestro_clave, maestro_sexo, maestro_celular, maestro_registro, maestro_email) VALUES (55, 'Sánchez', NULL, 'Orlando', 'orlando', 'eR5%tY9^uO3&', 0, NULL, '2026-01-23', NULL);
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (10, 6, 13, 'ABC', '2017-02-11');
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (11, 6, 14, 'ABC', '2017-02-11');
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (12, 6, 15, 'ABC', '2017-02-11');
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (13, 8, 16, 'ABC', '2017-02-11');
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (14, 8, 17, 'AB', '2017-02-11');
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (16, 25, 19, 'ABC', '2017-02-11');
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (17, 25, 20, 'ABC', '2017-02-11');
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (18, 25, 21, 'ABC', '2017-02-11');
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (20, 11, 26, 'ABC', '2017-02-11');
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (21, 11, 22, 'ABC', '2017-02-11');
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (22, 11, 23, 'ABC', '2017-02-11');
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (66, 24, 48, 'ABC', '2018-10-26');
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (67, 24, 49, 'ABC', '2018-10-26');
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (68, 24, 50, 'ABC', '2018-10-26');
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (75, 31, 10, 'ABC', '2023-09-15');
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (76, 31, 11, 'ABC', '2023-09-15');
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (77, 31, 12, 'ABC', '2023-09-15');
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (86, 34, 1, 'A', '2021-10-19');
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (87, 34, 2, 'ABC', '2021-10-19');
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (96, 37, 37, 'ABC', '2017-02-18');
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (97, 37, 38, 'ABC', '2017-02-17');
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (98, 37, 52, 'ABC', '2018-10-24');
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (99, 37, 27, 'ABC', '2021-10-19');
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (100, 37, 28, 'ABC', '2021-10-19');
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (101, 37, 29, 'ABC', '2021-10-19');
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (111, 40, 10, 'ABC', NULL);
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (113, 40, 11, 'ABC', NULL);
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (114, 40, 12, 'ABC', NULL);
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (115, 40, 13, 'ABC', NULL);
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (116, 40, 14, 'ABC', NULL);
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (117, 40, 15, 'ABC', NULL);
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (118, 40, 16, 'ABC', NULL);
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (119, 40, 17, 'ABC', NULL);
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (120, 40, 18, 'ABC', NULL);
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (121, 40, 19, 'ABC', NULL);
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (122, 40, 20, 'ABC', NULL);
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (123, 40, 21, 'ABC', NULL);
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (124, 40, 22, 'ABC', NULL);
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (125, 40, 23, 'ABC', NULL);
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (126, 40, 24, 'ABC', NULL);
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (127, 40, 25, 'ABC', NULL);
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (128, 40, 26, 'ABC', NULL);
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (135, 40, 39, 'ABC', NULL);
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (136, 40, 43, 'ABC', NULL);
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (137, 40, 44, 'ABC', NULL);
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (138, 40, 45, 'ABC', NULL);
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (139, 40, 46, 'ABC', NULL);
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (140, 40, 47, 'ABC', NULL);
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (141, 40, 48, 'ABC', NULL);
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (142, 40, 49, 'ABC', NULL);
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (143, 40, 50, 'ABC', NULL);
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (145, 40, 9, 'ABC', NULL);
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (146, 40, 7, 'ABC', NULL);
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (147, 40, 6, 'ABC', NULL);
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (148, 40, 5, 'ABC', NULL);
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (149, 40, 4, 'ABC', NULL);
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (150, 40, 3, 'ABC', NULL);
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (151, 40, 2, 'ABC', NULL);
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (152, 40, 1, 'ABC', NULL);
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (154, 34, 3, 'ABC', '2021-10-19');
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (165, 41, 4, 'B', '2023-09-15');
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (167, 41, 5, 'ABC', '2023-09-15');
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (168, 42, 7, 'AB', '2023-09-15');
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (169, 42, 9, 'ABC', '2023-09-15');
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (177, 8, 53, 'ABC', '2023-09-15');
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (178, 8, 54, 'ABC', '2023-09-15');
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (183, 40, 53, 'ABC', NULL);
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (184, 40, 54, 'ABC', NULL);
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (185, 40, 55, 'ABC', NULL);
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (189, 47, 2, 'A', '2024-09-04');
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (190, 47, 3, 'C', '2024-09-04');
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (191, 47, 39, 'C', '2024-09-04');
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (192, 49, 9, 'B', '2024-09-04');
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (193, 49, 5, 'BC', '2024-09-04');
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (194, 49, 6, 'A', '2024-09-04');
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (195, 50, 52, 'A', '2024-09-04');
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (196, 50, 37, 'A', '2024-09-04');
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (197, 50, 38, 'A', '2024-09-04');
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (200, 51, 53, 'ABC', '2024-09-04');
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (201, 51, 54, 'ABC', '2024-09-04');
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (202, 51, 55, 'ABC', '2024-09-04');
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (203, 42, 43, 'BC', '2024-09-05');
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (204, 41, 6, 'ABC', '2024-09-05');
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (205, 24, 17, 'C', '2024-09-05');
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (206, 24, 18, 'ABC', '2024-09-05');
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (207, 8, 55, 'ABC', '2024-09-12');
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (208, 52, 4, 'A', '2025-09-17');
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (209, 52, 43, 'A', '2025-09-17');
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (210, 52, 1, 'B', '2025-09-17');
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (212, 51, 16, 'ABC', '2025-09-17');
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (213, 51, 17, 'ABC', '2025-09-17');
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (214, 53, 18, 'ABC', '2025-09-17');
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (215, 53, 48, 'ABC', '2025-09-17');
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (216, 53, 49, 'ABC', '2025-09-17');
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (217, 53, 50, 'ABC', '2025-09-17');
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (218, 54, 45, 'ABC', '2025-09-17');
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (219, 54, 46, 'ABC', '2025-09-17');
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (220, 54, 47, 'ABC', '2025-09-17');
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (221, 11, 25, 'AB', NULL);
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (222, 11, 44, 'ABC', NULL);
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (223, 55, 39, 'ABC', '2026-01-23');
INSERT INTO boleta_maestro_grupo (grupo_id, maestro_id, materia_id, grupo_letra, grupo_registro) VALUES (224, 55, 24, 'AB', '2026-01-23');
INSERT INTO usuario (usuario_id, perfil_id, usuario_app, usuario_apm, usuario_nombre, usuario_username, usuario_email, usuario_password, usuario_status, nivel) VALUES (1, 1, 'ADMIN', 'BOLETAS', 'Administrador', 'admin', NULL, '21232f297a57a5a743894a0e4a801fc3', 1, 1) ON CONFLICT (usuario_id) DO NOTHING;
COMMIT;
