-- Tabla alumno_contacto (añadir a Supabase si ya migraste alumno / detalles / familiar)
-- Ejecutar en Supabase SQL Editor si la tabla aún no existe.

CREATE OR REPLACE FUNCTION public.set_contacto_updated_at_timestamp()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.contacto_actualizacion := CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$;

CREATE TABLE IF NOT EXISTS public.alumno_contacto (
  contacto_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alumno_id INTEGER NOT NULL,
  tutor_id SMALLINT NULL,
  tutor_clase VARCHAR(30) NULL,
  contacto_tipo SMALLINT NOT NULL,
  contacto_nombre VARCHAR(100) NULL,
  contacto_tel VARCHAR(20) NULL,
  contacto_cel VARCHAR(50) NULL,
  contacto_alta TIMESTAMP NULL,
  contacto_actualizacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON COLUMN public.alumno_contacto.contacto_tipo IS '1 = Contacto de emergencias; 2 = Persona autorizada';

CREATE INDEX IF NOT EXISTS alumno_contacto_alumno_id ON public.alumno_contacto (alumno_id);
CREATE INDEX IF NOT EXISTS alumno_contacto_alumno_tipo ON public.alumno_contacto (alumno_id, contacto_tipo);

DROP TRIGGER IF EXISTS trg_alumno_contacto_actualizacion ON public.alumno_contacto;
CREATE TRIGGER trg_alumno_contacto_actualizacion
  BEFORE UPDATE ON public.alumno_contacto
  FOR EACH ROW
  EXECUTE FUNCTION public.set_contacto_updated_at_timestamp();

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'alumno_contacto_alumno_id_fkey'
  ) THEN
    ALTER TABLE public.alumno_contacto
      ADD CONSTRAINT alumno_contacto_alumno_id_fkey
      FOREIGN KEY (alumno_id) REFERENCES public.alumno (alumno_id)
      ON DELETE RESTRICT ON UPDATE CASCADE;
  END IF;
END $$;
