-- =============================================================================
-- Tabla alumno_beca (MySQL winston_general → Supabase)
-- Ejecutar en Supabase SQL Editor después de tener public.alumno migrada.
--
-- Datos desde phpMyAdmin:
--   1. Exportar tabla alumno_beca → CSV (todas las filas)
--   2. node scripts/fix-alumno-beca-csv.mjs ruta/alumno_beca.csv
--   3. Table Editor → alumno_beca → Import → *_supabase.csv
--   4. Ejecutar el setval del final de este archivo
-- =============================================================================

CREATE OR REPLACE FUNCTION public.set_beca_updated_at_timestamp()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.beca_actualizacion := CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$;

CREATE TABLE IF NOT EXISTS public.alumno_beca (
  alumno_beca_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alumno_id INTEGER NOT NULL,
  beca_id SMALLINT NOT NULL,
  beca_porcentaje SMALLINT NOT NULL,
  beca_estatus SMALLINT NOT NULL,
  beca_ciclo_escolar SMALLINT NOT NULL,
  beca_registro TIMESTAMP NOT NULL,
  beca_actualizacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  beca_p VARCHAR(7) NOT NULL
);

COMMENT ON TABLE public.alumno_beca IS 'Becas asignadas por alumno y ciclo escolar (migrado desde MySQL).';
COMMENT ON COLUMN public.alumno_beca.beca_estatus IS '0 = Inactiva; 1 = Activa; 2 = En validación.';

-- Equivalente a índice UNIQUE alumno_id_2 en MySQL (un registro de beca por alumno en legacy)
CREATE UNIQUE INDEX IF NOT EXISTS alumno_beca_alumno_id_unique ON public.alumno_beca (alumno_id);

CREATE INDEX IF NOT EXISTS alumno_beca_alumno_id ON public.alumno_beca (alumno_id);
CREATE INDEX IF NOT EXISTS alumno_beca_beca_id ON public.alumno_beca (beca_id);
CREATE INDEX IF NOT EXISTS alumno_beca_ciclo ON public.alumno_beca (beca_ciclo_escolar);

DROP TRIGGER IF EXISTS trg_alumno_beca_actualizacion ON public.alumno_beca;
CREATE TRIGGER trg_alumno_beca_actualizacion
  BEFORE UPDATE ON public.alumno_beca
  FOR EACH ROW
  EXECUTE FUNCTION public.set_beca_updated_at_timestamp();

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'alumno_beca_alumno_id_fkey'
  ) THEN
    ALTER TABLE public.alumno_beca
      ADD CONSTRAINT alumno_beca_alumno_id_fkey
      FOREIGN KEY (alumno_id) REFERENCES public.alumno (alumno_id)
      ON DELETE RESTRICT ON UPDATE CASCADE;
  END IF;
END $$;

-- Tras migrar datos con IDs legacy, sincronizar secuencia (opcional):
-- SELECT setval(
--   pg_get_serial_sequence('public.alumno_beca', 'alumno_beca_id'),
--   COALESCE((SELECT MAX(alumno_beca_id) FROM public.alumno_beca), 1)
-- );
