-- =============================================================================
-- Migración alumno / alumno_detalles / alumno_familiar / alumno_contacto / alumno_beca (MySQL winston_general → Supabase)
-- Paso 2: esquema vacío alineado con phpMyAdmin
--
-- ANTES de ejecutar la sección "CREAR TABLAS":
--   1. Supabase Dashboard → SQL Editor
--   2. Renombrar tablas actuales (respaldo):
--        ALTER TABLE alumno RENAME TO alumno_old;
--        ALTER TABLE alumno_detalles RENAME TO alumno_detalles_old;
--        ALTER TABLE alumno_familiar RENAME TO alumno_familiar_old;
--        ALTER TABLE alumno_contacto RENAME TO alumno_contacto_old;
--        ALTER TABLE alumno_beca RENAME TO alumno_beca_old;
--   3. Ejecutar este archivo completo
--
-- Después de cargar datos (botón migración / ETL), al final del archivo hay
-- comandos opcionales para sincronizar secuencias de ID.
-- =============================================================================

-- Trigger reutilizable: equivalente a ON UPDATE CURRENT_TIMESTAMP (MySQL)
CREATE OR REPLACE FUNCTION public.set_updated_at_timestamp()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.alumno_actualizacion := CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.set_detalle_updated_at_timestamp()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.detalle_actualizacion := CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.set_familiar_updated_at_timestamp()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.familiar_actualizacion := CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.set_contacto_updated_at_timestamp()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.contacto_actualizacion := CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.set_beca_updated_at_timestamp()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.beca_actualizacion := CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$;

-- =============================================================================
-- CREAR TABLAS
-- =============================================================================

CREATE TABLE public.alumno (
  alumno_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alumno_ref INTEGER NULL,
  alumno_app VARCHAR(50) NULL,
  alumno_apm VARCHAR(50) NULL,
  alumno_nombre VARCHAR(50) NULL,
  alumno_nivel SMALLINT NULL,
  alumno_grado SMALLINT NULL,
  alumno_grupo SMALLINT NULL,
  alumno_status SMALLINT NOT NULL,
  alumno_nuevo_ingreso SMALLINT NOT NULL,
  alumno_ciclo_escolar SMALLINT NULL,
  alumno_registro DATE NULL,
  alumno_alta DATE NULL,
  alumno_actualizacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  alumno_boleta SMALLINT NOT NULL,
  mes SMALLINT NOT NULL,
  secret_key VARCHAR(64) NOT NULL,
  motivo VARCHAR(200) NOT NULL,
  responsable VARCHAR(50) NOT NULL,
  estatus_key SMALLINT NOT NULL DEFAULT 0,
  digito INTEGER NOT NULL,
  hijo SMALLINT NOT NULL DEFAULT 0
);

COMMENT ON COLUMN public.alumno.alumno_nivel IS '1= Maternal; 2= Kinder; 3= Primaria; 4= Secundaria';
COMMENT ON COLUMN public.alumno.alumno_status IS '0= Baja General; 1= Activo; 2= Inactivo; 3= Baja Temporal Administrativa; 5= Bloqueo por Psicología';
COMMENT ON COLUMN public.alumno.alumno_nuevo_ingreso IS '0= Reinscrito; 1= Nuevo Ingreso de Agenda';
COMMENT ON COLUMN public.alumno.alumno_ciclo_escolar IS '12= 2015-2016; 13= 2016-2017; 14= 2017-2018; …';
COMMENT ON COLUMN public.alumno.alumno_registro IS 'Registro de la Solicitud de Inscripción; NULL si no ha realizado la solicitud';
COMMENT ON COLUMN public.alumno.alumno_alta IS 'Alta del pase de agenda';

CREATE UNIQUE INDEX alumno_ref ON public.alumno (alumno_ref);

CREATE TRIGGER trg_alumno_actualizacion
  BEFORE UPDATE ON public.alumno
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at_timestamp();

-- -----------------------------------------------------------------------------

CREATE TABLE public.alumno_detalles (
  detalle_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alumno_id INTEGER NULL,
  alumno_clave VARCHAR(20) NULL,
  alumno_fecha_nac DATE NULL,
  alumno_lugar_nac VARCHAR(50) NULL,
  alumno_curp VARCHAR(18) NULL,
  alumno_sexo CHAR(1) NULL,
  alumno_calle VARCHAR(100) NULL,
  alumno_numero VARCHAR(50) NULL,
  alumno_numeroint VARCHAR(50) NULL,
  alumno_colonia VARCHAR(100) NULL,
  alumno_cp INTEGER NULL,
  alumno_entre_calles VARCHAR(150) NULL,
  estado_id VARCHAR(200) NULL,
  cuidad_id VARCHAR(200) NULL,
  alumno_escuela_procedente VARCHAR(50) NULL,
  tipo_relacion INTEGER NULL,
  comentario_relacion VARCHAR(100) NULL,
  detalle_registro TIMESTAMP NULL,
  detalle_actualizacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON COLUMN public.alumno_detalles.alumno_sexo IS 'H= Hombre; M= Mujer';
COMMENT ON COLUMN public.alumno_detalles.tipo_relacion IS 'Relación entre tutores';
COMMENT ON COLUMN public.alumno_detalles.comentario_relacion IS 'Comentario sobre relación de tutores';

CREATE UNIQUE INDEX alumno_detalles_alumno_id ON public.alumno_detalles (alumno_id);

CREATE TRIGGER trg_alumno_detalles_actualizacion
  BEFORE UPDATE ON public.alumno_detalles
  FOR EACH ROW
  EXECUTE FUNCTION public.set_detalle_updated_at_timestamp();

-- -----------------------------------------------------------------------------

CREATE TABLE public.alumno_familiar (
  familiar_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alumno_id INTEGER NULL,
  tutor_id SMALLINT NULL,
  familiar_app VARCHAR(50) NULL,
  familiar_apm VARCHAR(50) NULL,
  familiar_nombre VARCHAR(50) NULL,
  familiar_tel VARCHAR(20) NULL,
  familiar_cel VARCHAR(20) NULL,
  familiar_email VARCHAR(100) NULL,
  familiar_recibir_email SMALLINT NOT NULL,
  familiar_fecha_nac DATE NULL,
  familiar_lugar_nac VARCHAR(50) NULL,
  familiar_curp VARCHAR(18) NULL,
  familiar_escolaridad VARCHAR(50) NULL,
  familiar_empresa_nombre VARCHAR(100) NULL,
  familiar_empresa_direccion VARCHAR(200) NULL,
  familiar_empresa_puesto VARCHAR(100) NULL,
  familiar_empresa_tel VARCHAR(20) NULL,
  familiar_vive SMALLINT NOT NULL,
  familiar_registro DATE NULL,
  familiar_actualizacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  familiar_rfc VARCHAR(13) NULL,
  familiar_factura SMALLINT NOT NULL
);

CREATE INDEX alumno_familiar_tutor_id ON public.alumno_familiar (tutor_id);
CREATE INDEX alumno_familiar_alumno_id ON public.alumno_familiar (alumno_id);

CREATE TRIGGER trg_alumno_familiar_actualizacion
  BEFORE UPDATE ON public.alumno_familiar
  FOR EACH ROW
  EXECUTE FUNCTION public.set_familiar_updated_at_timestamp();

-- -----------------------------------------------------------------------------

CREATE TABLE public.alumno_contacto (
  contacto_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alumno_id INTEGER NOT NULL,
  tutor_id SMALLINT NULL,
  tutor_clase VARCHAR(30) NULL,
  contacto_tipo SMALLINT NOT NULL,
  contacto_nombre VARCHAR(100) NULL,
  contacto_tel VARCHAR(20) NULL,
  contacto_cel VARCHAR(50) NULL,
  contacto_alta TIMESTAMP NULL,
  contacto_actualizacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON COLUMN public.alumno_contacto.contacto_tipo IS '1 = Contacto de emergencias; 2 = Persona autorizada';
COMMENT ON COLUMN public.alumno_contacto.tutor_clase IS 'Parentesco (ej. ABUELA, TIA)';

CREATE INDEX alumno_contacto_alumno_id ON public.alumno_contacto (alumno_id);
CREATE INDEX alumno_contacto_alumno_tipo ON public.alumno_contacto (alumno_id, contacto_tipo);

CREATE TRIGGER trg_alumno_contacto_actualizacion
  BEFORE UPDATE ON public.alumno_contacto
  FOR EACH ROW
  EXECUTE FUNCTION public.set_contacto_updated_at_timestamp();

-- -----------------------------------------------------------------------------

CREATE TABLE public.alumno_beca (
  alumno_beca_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alumno_id INTEGER NOT NULL,
  beca_id SMALLINT NOT NULL,
  beca_porcentaje SMALLINT NOT NULL,
  beca_estatus SMALLINT NOT NULL,
  beca_ciclo_escolar SMALLINT NOT NULL,
  beca_registro TIMESTAMP NOT NULL,
  beca_actualizacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  beca_p VARCHAR(7) NOT NULL
);

COMMENT ON TABLE public.alumno_beca IS 'Becas asignadas por alumno y ciclo escolar (MySQL winston_general.alumno_beca).';
COMMENT ON COLUMN public.alumno_beca.beca_estatus IS '0 = Inactiva; 1 = Activa; 2 = En validación.';

CREATE UNIQUE INDEX alumno_beca_alumno_id_unique ON public.alumno_beca (alumno_id);
CREATE INDEX alumno_beca_alumno_id ON public.alumno_beca (alumno_id);
CREATE INDEX alumno_beca_beca_id ON public.alumno_beca (beca_id);
CREATE INDEX alumno_beca_ciclo ON public.alumno_beca (beca_ciclo_escolar);

CREATE TRIGGER trg_alumno_beca_actualizacion
  BEFORE UPDATE ON public.alumno_beca
  FOR EACH ROW
  EXECUTE FUNCTION public.set_beca_updated_at_timestamp();

-- =============================================================================
-- Claves foráneas (después de tener tablas vacías; la carga respeta este orden)
-- =============================================================================

ALTER TABLE public.alumno_detalles
  ADD CONSTRAINT alumno_detalles_alumno_id_fkey
  FOREIGN KEY (alumno_id) REFERENCES public.alumno (alumno_id)
  ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE public.alumno_familiar
  ADD CONSTRAINT alumno_familiar_alumno_id_fkey
  FOREIGN KEY (alumno_id) REFERENCES public.alumno (alumno_id)
  ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE public.alumno_contacto
  ADD CONSTRAINT alumno_contacto_alumno_id_fkey
  FOREIGN KEY (alumno_id) REFERENCES public.alumno (alumno_id)
  ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE public.alumno_beca
  ADD CONSTRAINT alumno_beca_alumno_id_fkey
  FOREIGN KEY (alumno_id) REFERENCES public.alumno (alumno_id)
  ON DELETE RESTRICT ON UPDATE CASCADE;

-- =============================================================================
-- RLS (Supabase): descomenta si usas anon key desde el cliente
-- =============================================================================
-- ALTER TABLE public.alumno ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.alumno_detalles ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.alumno_familiar ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.alumno_contacto ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.alumno_beca ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY "lectura autenticados" ON public.alumno FOR SELECT TO authenticated USING (true);
-- (repite políticas según tu auth)

-- =============================================================================
-- OPCIONAL — ejecutar DESPUÉS de importar datos desde MySQL
-- Ajusta secuencias al máximo id insertado (como AUTO_INCREMENT en MySQL)
-- =============================================================================
/*
SELECT setval(pg_get_serial_sequence('public.alumno', 'alumno_id'), COALESCE((SELECT MAX(alumno_id) FROM public.alumno), 1));
SELECT setval(pg_get_serial_sequence('public.alumno_detalles', 'detalle_id'), COALESCE((SELECT MAX(detalle_id) FROM public.alumno_detalles), 1));
SELECT setval(pg_get_serial_sequence('public.alumno_familiar', 'familiar_id'), COALESCE((SELECT MAX(familiar_id) FROM public.alumno_familiar), 1));
SELECT setval(pg_get_serial_sequence('public.alumno_contacto', 'contacto_id'), COALESCE((SELECT MAX(contacto_id) FROM public.alumno_contacto), 1));
SELECT setval(pg_get_serial_sequence('public.alumno_beca', 'alumno_beca_id'), COALESCE((SELECT MAX(alumno_beca_id) FROM public.alumno_beca), 1));
*/
